--
-- Datenbank für Modul 3 Abschlussprojekt
--
DROP DATABASE IF EXISTS interessenten_db;
CREATE DATABASE interessenten_db;
GO

--
-- Tabelle interessenten
--

DROP TABLE IF EXISTS interessenten;
CREATE TABLE interessenten (
  Interessent_id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Standort VARCHAR(20) DEFAULT NULL,
  PLZ CHAR(5) DEFAULT NULL,
  Adresse_Standort VARCHAR(20) DEFAULT NULL,
  KFZ CHAR(4) DEFAULT NULL,
  Abteilung VARCHAR(20) DEFAULT NULL,
  Anrede VARCHAR(15) DEFAULT NULL,
  Vorname VARCHAR(30) NOT NULL,
  Nachname VARCHAR(40) NOT NULL,
  EMail VARCHAR(60) NOT NULL,
  Benutzeranmeldename VARCHAR(30) NOT NULL
);

INSERT INTO interessenten(Standort, PLZ, Adresse_Standort, KFZ, Abteilung, Anrede, Vorname, Nachname, EMail, Benutzeranmeldename) VALUES 
('Hamburg','20144','Musterstraße 1','HH','Verwaltung','Dipl.-Ing.','Christina','Boucsein','christina.boucsein@HH.zukunftsmotor.local','christina.boucsein'),
('Hamburg','20144','Musterstraße 1','HH','Verwaltung','Dr.','Guido','Steckel','guido.steckel@HH.zukunftsmotor.local','guido.steckel'),
('Hamburg','20144','Musterstraße 1','HH','LX','Univ.Prof.','Gerlinde','Ruppersberger','gerlinde.ruppersberger@HH.zukunftsmotor.local','gerlinde.ruppersberger'),
('Hamburg','20144','Musterstraße 1','HH','LX','Dipl.-Ing.','Hans-Peter','Wirth','hans-peter.wirth@HH.zukunftsmotor.local','hans-peter.wirth'),
('Hamburg','20144','Musterstraße 1','HH','Kurs1','Dr.','Evi','Henk','evi.henk@HH.zukunftsmotor.local','evi.henk'),
('Hamburg','20144','Musterstraße 1','HH','Kurs1','Dipl.-Ing.','Harm','Lehmann','harm.lehmann@HH.zukunftsmotor.local','harm.lehmann'),
('Hamburg','20144','Musterstraße 1','HH','Kurs2','Ing.','Cecilia','Junken','cecilia.junken@HH.zukunftsmotor.local','cecilia.junken'),
('Hamburg','20144','Musterstraße 1','HH','Kurs2','Univ.Prof.','Frank-Peter','Schenk','frank-peter.schenk@HH.zukunftsmotor.local','frank-peter.schenk'),
('Hamburg','20144','Musterstraße 1','HH','Kurs3','Dr.','Diane','Pärtzelt','diane.pärtzelt@HH.zukunftsmotor.local','diane.pärtzelt'),
('Hamburg','20144','Musterstraße 1','HH','Kurs3','Prof.','Lilian','Holt','lilian.holt@HH.zukunftsmotor.local','lilian.holt'),
('Hamburg','20144','Musterstraße 1','HH','Kurs4','Univ.Prof.','Heinfried','Hauffer','heinfried.hauffer@HH.zukunftsmotor.local','heinfried.hauffer'),
('Hamburg','20144','Musterstraße 1','HH','Kurs4','Ing.','Anatolij','Berger','anatolij.berger@HH.zukunftsmotor.local','anatolij.berger'),
('Hamburg','20144','Musterstraße 1','HH','IT','Univ.Prof.','Luise','Wieloch','luise.wieloch@HH.zukunftsmotor.local','luise.wieloch'),
('Hamburg','20144','Musterstraße 1','HH','IT','Univ.Prof.','Hans-Hinrich','Bärer','hans-hinrich.bärer@HH.zukunftsmotor.local','hans-hinrich.bärer'),
('Düsseldorf','44001','Beispielweg 2','D','Verwaltung','Frau','Danilo','Schuchhardt','danilo.schuchhardt@D.zukunftsmotor.local','danilo.schuchhardt'),
('Düsseldorf','44001','Beispielweg 2','D','Verwaltung','Univ.Prof.','Ursula','Jäntsch','ursula.jäntsch@D.zukunftsmotor.local','ursula.jäntsch'),
('Düsseldorf','44001','Beispielweg 2','D','LX','Herr','Katalin','Stroh','katalin.stroh@D.zukunftsmotor.local','katalin.stroh'),
('Düsseldorf','44001','Beispielweg 2','D','LX','Univ.Prof.','Igor','Kruschwitz','igor.kruschwitz@D.zukunftsmotor.local','igor.kruschwitz'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs1','Dipl.-Ing.','Dolores','Mangold','dolores.mangold@D.zukunftsmotor.local','dolores.mangold'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs1','Dipl.-Ing.','Zeynep','Seip','zeynep.seip@D.zukunftsmotor.local','zeynep.seip'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs2','Dr.','Bruni','Pieper','bruni.pieper@D.zukunftsmotor.local','bruni.pieper'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs2','Dipl.-Ing.','Jadwiga','Stey','jadwiga.stey@D.zukunftsmotor.local','jadwiga.stey'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs3','Dipl.-Ing.','Raik','Carsten','raik.carsten@D.zukunftsmotor.local','raik.carsten'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs3','Univ.Prof.','Sergio','Ullrich','sergio.ullrich@D.zukunftsmotor.local','sergio.ullrich'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs4','Prof.','Luisa','Pölitz','luisa.pölitz@D.zukunftsmotor.local','luisa.pölitz'),
('Düsseldorf','44001','Beispielweg 2','D','Kurs4','Dr.','Severin','Kade','severin.kade@D.zukunftsmotor.local','severin.kade'),
('Düsseldorf','44001','Beispielweg 2','D','IT','Herr','Rotraud','Pölitz','rotraud.pölitz@D.zukunftsmotor.local','rotraud.pölitz'),
('Düsseldorf','44001','Beispielweg 2','D','IT','Prof.','Hans-Herbert','Rörricht','hans-herbert.rörricht@D.zukunftsmotor.local','hans-herbert.rörricht'),
('Berlin','10247','Testgasse 3','B','Verwaltung','Ing.','Robby','Wesack','robby.wesack@B.zukunftsmotor.local','robby.wesack'),
('Berlin','10247','Testgasse 3','B','Verwaltung','Dr.','Maurice','Mende','maurice.mende@B.zukunftsmotor.local','maurice.mende'),
('Berlin','10247','Testgasse 3','B','LX','Prof.','Rosalia','Täsche','rosalia.täsche@B.zukunftsmotor.local','rosalia.täsche'),
('Berlin','10247','Testgasse 3','B','LX','Frau','Annelene','Kade','annelene.kade@B.zukunftsmotor.local','annelene.kade'),
('Berlin','10247','Testgasse 3','B','Kurs1','Dr.','Suzanne','Heydrich','suzanne.heydrich@B.zukunftsmotor.local','suzanne.heydrich'),
('Berlin','10247','Testgasse 3','B','Kurs1','Ing.','Hansgeorg','Thanel','hansgeorg.thanel@B.zukunftsmotor.local','hansgeorg.thanel'),
('Berlin','10247','Testgasse 3','B','Kurs2','Prof.','Rosemarie','Dowerg','rosemarie.dowerg@B.zukunftsmotor.local','rosemarie.dowerg'),
('Berlin','10247','Testgasse 3','B','Kurs2','Univ.Prof.','Balthasar','Pölitz','balthasar.pölitz@B.zukunftsmotor.local','balthasar.pölitz'),
('Berlin','10247','Testgasse 3','B','Kurs3','Ing.','Jeannine','Herrmann','jeannine.herrmann@B.zukunftsmotor.local','jeannine.herrmann'),
('Berlin','10247','Testgasse 3','B','Kurs3','Univ.Prof.','Franz-Peter','Lindner','franz-peter.lindner@B.zukunftsmotor.local','franz-peter.lindner'),
('Berlin','10247','Testgasse 3','B','Kurs4','Dr.','Elke','Heinrich','elke.heinrich@B.zukunftsmotor.local','elke.heinrich'),
('Berlin','10247','Testgasse 3','B','Kurs4','Frau','Vassilios','Finke','vassilios.finke@B.zukunftsmotor.local','vassilios.finke'),
('Berlin','10247','Testgasse 3','B','IT','Ing.','Delia','Pergande','delia.pergande@B.zukunftsmotor.local','delia.pergande'),
('Berlin','10247','Testgasse 3','B','IT','Dipl.-Ing.','Burkard','Schüler','burkard.schüler@B.zukunftsmotor.local','burkard.schüler'),
('Frankfurt','60320','Musterweg 4','F','Verwaltung','Dr.','Hans-Rudolf','Steinberg','hans-rudolf.steinberg@F.zukunftsmotor.local','hans-rudolf.steinberg'),
('Frankfurt','60320','Musterweg 4','F','Verwaltung','Univ.Prof.','Desiree','Juncken','desiree.juncken@F.zukunftsmotor.local','desiree.juncken'),
('Frankfurt','60320','Musterweg 4','F','LX','Ing.','Natalie','Jessel','natalie.jessel@F.zukunftsmotor.local','natalie.jessel'),
('Frankfurt','60320','Musterweg 4','F','LX','Dipl.-Ing.','Lore','Heuser','lore.heuser@F.zukunftsmotor.local','lore.heuser'),
('Frankfurt','60320','Musterweg 4','F','Kurs1','Prof.','Hendrik','Kambs','hendrik.kambs@F.zukunftsmotor.local','hendrik.kambs'),
('Frankfurt','60320','Musterweg 4','F','Kurs1','Prof.','Adina','Holsten','adina.holsten@F.zukunftsmotor.local','adina.holsten'),
('Frankfurt','60320','Musterweg 4','F','Kurs2','Prof.','Janos','Mans','janos.mans@F.zukunftsmotor.local','janos.mans'),
('Frankfurt','60320','Musterweg 4','F','Kurs2','Ing.','Chantal','Schmidt','chantal.schmidt@F.zukunftsmotor.local','chantal.schmidt'),
('Frankfurt','60320','Musterweg 4','F','Kurs3','Ing.','Tino','Christoph','tino.christoph@F.zukunftsmotor.local','tino.christoph'),
('Frankfurt','60320','Musterweg 4','F','Kurs3','Frau','Kaspar','Klemm','kaspar.klemm@F.zukunftsmotor.local','kaspar.klemm'),
('Frankfurt','60320','Musterweg 4','F','Kurs4','Univ.Prof.','Athanasios','Liebelt','athanasios.liebelt@F.zukunftsmotor.local','athanasios.liebelt'),
('Frankfurt','60320','Musterweg 4','F','Kurs4','Dr.','Gunther','Pechel','gunther.pechel@F.zukunftsmotor.local','gunther.pechel'),
('Frankfurt','60320','Musterweg 4','F','IT','Dipl.-Ing.','Karl-Heinrich','Hänel','karl-heinrich.hänel@F.zukunftsmotor.local','karl-heinrich.hänel'),
('Frankfurt','60320','Musterweg 4','F','IT','Herr','Aleksandr','Hoffmann','aleksandr.hoffmann@F.zukunftsmotor.local','aleksandr.hoffmann'),
('Stuttgart','70177','Beispielstraße 5','S','Verwaltung','Ing.','Hartmut','Kade','hartmut.kade@S.zukunftsmotor.local','hartmut.kade'),
('Stuttgart','70177','Beispielstraße 5','S','Verwaltung','Dr.','Sandy','Schlosser','sandy.schlosser@S.zukunftsmotor.local','sandy.schlosser'),
('Stuttgart','70177','Beispielstraße 5','S','LX','Frau','Traude','Killer','traude.killer@S.zukunftsmotor.local','traude.killer'),
('Stuttgart','70177','Beispielstraße 5','S','LX','Dr.','Traudl','Finke','traudl.finke@S.zukunftsmotor.local','traudl.finke'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs1','Prof.','Birger','Dippel','birger.dippel@S.zukunftsmotor.local','birger.dippel'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs1','Frau','Nelly','Reuter','nelly.reuter@S.zukunftsmotor.local','nelly.reuter'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs2','Univ.Prof.','Anastasia','Eberth','anastasia.eberth@S.zukunftsmotor.local','anastasia.eberth'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs2','Univ.Prof.','Nicole','Putz','nicole.putz@S.zukunftsmotor.local','nicole.putz'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs3','Dr.','Tülay','Pieper','tülay.pieper@S.zukunftsmotor.local','tülay.pieper'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs3','Frau','Amanda','Scholl','amanda.scholl@S.zukunftsmotor.local','amanda.scholl'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs4','Ing.','Baldur','Matthäi','baldur.matthäi@S.zukunftsmotor.local','baldur.matthäi'),
('Stuttgart','70177','Beispielstraße 5','S','Kurs4','Ing.','Hubert','Holzapfel','hubert.holzapfel@S.zukunftsmotor.local','hubert.holzapfel'),
('Stuttgart','70177','Beispielstraße 5','S','IT','Univ.Prof.','Notburga','Schüler','notburga.schüler@S.zukunftsmotor.local','notburga.schüler'),
('Stuttgart','70177','Beispielstraße 5','S','IT','Frau','Constance','Wagner','constance.wagner@S.zukunftsmotor.local','constance.wagner'),
('München','80331','Testweg 6','M','Verwaltung','Dr.','René','Birnbaum','rené.birnbaum@M.zukunftsmotor.local','rené.birnbaum'),
('München','80331','Testweg 6','M','Verwaltung','Ing.','Jaqueline','Wilmsen','jaqueline.wilmsen@M.zukunftsmotor.local','jaqueline.wilmsen'),
('München','80331','Testweg 6','M','LX','Dr.','Etta','Holt','etta.holt@M.zukunftsmotor.local','etta.holt'),
('München','80331','Testweg 6','M','LX','Dipl.-Ing.','Siegrid','Carsten','siegrid.carsten@M.zukunftsmotor.local','siegrid.carsten'),
('München','80331','Testweg 6','M','Kurs1','Dipl.-Ing.','Yilmaz','Vollbrecht','yilmaz.vollbrecht@M.zukunftsmotor.local','yilmaz.vollbrecht'),
('München','80331','Testweg 6','M','Kurs1','Prof.','Erich','Ullrich','erich.ullrich@M.zukunftsmotor.local','erich.ullrich'),
('München','80331','Testweg 6','M','Kurs2','Univ.Prof.','Mareike','Heydrich','mareike.heydrich@M.zukunftsmotor.local','mareike.heydrich'),
('München','80331','Testweg 6','M','Kurs2','Prof.','Swantje','Bolzmann','swantje.bolzmann@M.zukunftsmotor.local','swantje.bolzmann'),
('München','80331','Testweg 6','M','Kurs3','Prof.','Othmar','Dobes','othmar.dobes@M.zukunftsmotor.local','othmar.dobes'),
('München','80331','Testweg 6','M','Kurs3','Ing.','Andy','Ziegert','andy.ziegert@M.zukunftsmotor.local','andy.ziegert'),
('München','80331','Testweg 6','M','Kurs4','Frau','Sibel','Butte','sibel.butte@M.zukunftsmotor.local','sibel.butte'),
('München','80331','Testweg 6','M','Kurs4','Univ.Prof.','Miroslaw','Bachmann','miroslaw.bachmann@M.zukunftsmotor.local','miroslaw.bachmann'),
('München','80331','Testweg 6','M','IT','Dipl.-Ing.','Thilo','Höfig','thilo.höfig@M.zukunftsmotor.local','thilo.höfig'),
('München','80331','Testweg 6','M','IT','Prof.','Bertram','Reuter','bertram.reuter@M.zukunftsmotor.local','bertram.reuter'),
('Nürnberg','90402','Musterplatz 7','N','Verwaltung','Univ.Prof.','Bozena','Albers','bozena.albers@N.zukunftsmotor.local','bozena.albers'),
('Nürnberg','90402','Musterplatz 7','N','Verwaltung','Herr','Ilonka','Girschner','ilonka.girschner@N.zukunftsmotor.local','ilonka.girschner'),
('Nürnberg','90402','Musterplatz 7','N','LX','Herr','Sigrun','van der Dussen','sigrun.van der dussen@N.zukunftsmotor.local','sigrun.van der dussen'),
('Nürnberg','90402','Musterplatz 7','N','LX','Univ.Prof.','Iwona','Reinhardt','iwona.reinhardt@N.zukunftsmotor.local','iwona.reinhardt'),
('Nürnberg','90402','Musterplatz 7','N','Kurs1','Univ.Prof.','Nada','Eigenwillig','nada.eigenwillig@N.zukunftsmotor.local','nada.eigenwillig'),
('Nürnberg','90402','Musterplatz 7','N','Kurs1','Ing.','Sevim','Pohl','sevim.pohl@N.zukunftsmotor.local','sevim.pohl'),
('Nürnberg','90402','Musterplatz 7','N','Kurs2','Ing.','Danielle','Schäfer','danielle.schäfer@N.zukunftsmotor.local','danielle.schäfer'),
('Nürnberg','90402','Musterplatz 7','N','Kurs2','Dr.','Marten','Schweitzer','marten.schweitzer@N.zukunftsmotor.local','marten.schweitzer'),
('Nürnberg','90402','Musterplatz 7','N','Kurs3','Univ.Prof.','Oskar','Seip','oskar.seip@N.zukunftsmotor.local','oskar.seip'),
('Nürnberg','90402','Musterplatz 7','N','Kurs3','Ing.','Anke','Pieper','anke.pieper@N.zukunftsmotor.local','anke.pieper'),
('Nürnberg','90402','Musterplatz 7','N','Kurs4','Frau','Steve','Schlosser','steve.schlosser@N.zukunftsmotor.local','steve.schlosser'),
('Nürnberg','90402','Musterplatz 7','N','Kurs4','Herr','Hans-Karl','Aumann','hans-karl.aumann@N.zukunftsmotor.local','hans_karl.aumann'),
('Nürnberg','90402','Musterplatz 7','N','IT','Dipl.-Ing.','Gottlieb','Jacob','gottlieb.jacob@N.zukunftsmotor.local','gottlieb.jacob'),
('Nürnberg','90402','Musterplatz 7','N','IT','Dr.','Harriet','Börner','harriet.börner@N.zukunftsmotor.local','harriet.börner');


INSERT INTO interessenten(Standort, PLZ, Adresse_Standort, KFZ, Abteilung, Anrede, Vorname, Nachname, EMail, Benutzeranmeldename) VALUES 
('Erfurt','99084','Beispielpfad 8','EF','Verwaltung','Frau','Jovan','Scholz','jovan.scholz@EF.zukunftsmotor.local','jovan.scholz'),
('Erfurt','99084','Beispielpfad 8','EF','Verwaltung','Univ.Prof.','Massimo','Sager','massimo.sager@EF.zukunftsmotor.local','massimo.sager'),
('Erfurt','99084','Beispielpfad 8','EF','LX','Dipl.-Ing.','Gregor','Hornig','gregor.hornig@EF.zukunftsmotor.local','gregor.hornig'),
('Erfurt','99084','Beispielpfad 8','EF','LX','Univ.Prof.','Matthäus','Davids','matthäus.davids@EF.zukunftsmotor.local','matthäus.davids'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs1','Frau','Gottfried','Rädel','gottfried.rädel@EF.zukunftsmotor.local','gottfried.rädel'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs1','Herr','Christos','Gierschner','christos.gierschner@EF.zukunftsmotor.local','christos.gierschner'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs2','Frau','Robert','Bolzmann','robert.bolzmann@EF.zukunftsmotor.local','robert.bolzmann'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs2','Prof.','Felicia','Geisel','felicia.geisel@EF.zukunftsmotor.local','felicia.geisel'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs3','Univ.Prof.','Zoran','Schäfer','zoran.schäfer@EF.zukunftsmotor.local','zoran.schäfer'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs3','Frau','Otto','Werner','otto.werner@EF.zukunftsmotor.local','otto.werner'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs4','Univ.Prof.','Sönke','Jüttner','sönke.jüttner@EF.zukunftsmotor.local','sönke.jüttner'),
('Erfurt','99084','Beispielpfad 8','EF','Kurs4','Univ.Prof.','Maren','Warmer','maren.warmer@EF.zukunftsmotor.local','maren.warmer'),
('Erfurt','99084','Beispielpfad 8','EF','IT','Ing.','Alberto','Hermann','alberto.hermann@EF.zukunftsmotor.local','alberto.hermann'),
('Erfurt','99084','Beispielpfad 8','EF','IT','Prof.','Reimar','Wilms','reimar.wilms@EF.zukunftsmotor.local','reimar.wilms'),
('Dresden','01099','Testallee 9','DD','Verwaltung','Prof.','Stefan','Lehmann','stefan.lehmann@DD.zukunftsmotor.local','stefan.lehmann'),
('Dresden','01099','Testallee 9','DD','Verwaltung','Frau','Roderich','Hänel','roderich.hänel@DD.zukunftsmotor.local','roderich.hänel'),
('Dresden','01099','Testallee 9','DD','LX','Prof.','Esther','Schaaf','esther.schaaf@DD.zukunftsmotor.local','esther.schaaf'),
('Dresden','01099','Testallee 9','DD','LX','Prof.','Roberto','Blümel','roberto.blümel@DD.zukunftsmotor.local','roberto.blümel'),
('Dresden','01099','Testallee 9','DD','Kurs1','Prof.','Nikolai','Gierschner','nikolai.gierschner@DD.zukunftsmotor.local','nikolai.gierschner'),
('Dresden','01099','Testallee 9','DD','Kurs1','Dr.','Hedy','Otto','hedy.otto@DD.zukunftsmotor.local','hedy.otto'),
('Dresden','01099','Testallee 9','DD','Kurs2','Prof.','Stanislav','Röhricht','stanislav.röhricht@DD.zukunftsmotor.local','stanislav.röhricht'),
('Dresden','01099','Testallee 9','DD','Kurs2','Ing.','Gertraut','Scholz','gertraut.scholz@DD.zukunftsmotor.local','gertraut.scholz'),
('Dresden','01099','Testallee 9','DD','Kurs3','Dipl.-Ing.','Ingeborg','Schönland','ingeborg.schönland@DD.zukunftsmotor.local','ingeborg.schönland'),
('Dresden','01099','Testallee 9','DD','Kurs3','Univ.Prof.','Cecilia','Gierschner','cecilia.gierschner@DD.zukunftsmotor.local','cecilia.gierschner'),
('Dresden','01099','Testallee 9','DD','Kurs4','Dr.','Luise','Mende','luise.mende@DD.zukunftsmotor.local','luise.mende'),
('Dresden','01099','Testallee 9','DD','Kurs4','Dipl.-Ing.','Charlotte','Trub','charlotte.trub@DD.zukunftsmotor.local','charlotte.trub'),
('Dresden','01099','Testallee 9','DD','IT','Prof.','Britta','Henck','britta.henck@DD.zukunftsmotor.local','britta.henck'),
('Dresden','01099','Testallee 9','DD','IT','Univ.Prof.','Ella','Haase','ella.haase@DD.zukunftsmotor.local','ella.haase'),
('Hannover','30001','Musterweg 10','H','Verwaltung','Ing.','Attila','Rörricht','attila.rörricht@H.zukunftsmotor.local','attila.rörricht'),
('Hannover','30001','Musterweg 10','H','Verwaltung','Frau','Swetlana','Wilmsen','swetlana.wilmsen@H.zukunftsmotor.local','swetlana.wilmsen'),
('Hannover','30001','Musterweg 10','H','LX','Dipl.-Ing.','Adolf','Roht','adolf.roht@H.zukunftsmotor.local','adolf.roht'),
('Hannover','30001','Musterweg 10','H','LX','Frau','Sibilla','Hecker','sibilla.hecker@H.zukunftsmotor.local','sibilla.hecker'),
('Hannover','30001','Musterweg 10','H','Kurs1','Herr','Nora','Haering','nora.haering@H.zukunftsmotor.local','nora.haering'),
('Hannover','30001','Musterweg 10','H','Kurs1','Prof.','Klaus-Michael','Eckbauer','klaus-michael.eckbauer@H.zukunftsmotor.local','klaus-michael.eckbauer'),
('Hannover','30001','Musterweg 10','H','Kurs2','Dipl.-Ing.','Marten','Döhn','marten.döhn@H.zukunftsmotor.local','marten.döhn'),
('Hannover','30001','Musterweg 10','H','Kurs2','Frau','Annelore','Steckel','annelore.steckel@H.zukunftsmotor.local','annelore.steckel'),
('Hannover','30001','Musterweg 10','H','Kurs3','Univ.Prof.','Antonia','Wilmsen','antonia.wilmsen@H.zukunftsmotor.local','antonia.wilmsen'),
('Hannover','30001','Musterweg 10','H','Kurs3','Herr','Liesel','Heß','liesel.heß@H.zukunftsmotor.local','liesel.heß'),
('Hannover','30001','Musterweg 10','H','Kurs4','Dr.','Nevenka','Schinke','nevenka.schinke@H.zukunftsmotor.local','nevenka.schinke'),
('Hannover','30001','Musterweg 10','H','Kurs4','Univ.Prof.','Kuno','Butte','kuno.butte@H.zukunftsmotor.local','kuno.butte'),
('Hannover','30001','Musterweg 10','H','IT','Prof.','Tobias','Spieß','tobias.spieß@H.zukunftsmotor.local','tobias.spieß'),
('Hannover','30001','Musterweg 10','H','IT','Herr','Balthasar','Förster','balthasar.förster@H.zukunftsmotor.local','balthasar.förster'),
('Rostock','18001','Beispielpfad 11','HRO','Verwaltung','Herr','Wolfram','Roskoth','wolfram.roskoth@HRO.zukunftsmotor.local','wolfram.roskoth'),
('Rostock','18001','Beispielpfad 11','HRO','Verwaltung','Prof.','Kemal','Weihmann','kemal.weihmann@HRO.zukunftsmotor.local','kemal.weihmann'),
('Rostock','18001','Beispielpfad 11','HRO','LX','Ing.','Zofia','Bolander','zofia.bolander@HRO.zukunftsmotor.local','zofia.bolander'),
('Rostock','18001','Beispielpfad 11','HRO','LX','Prof.','Waltraud','Gnatz','waltraud.gnatz@HRO.zukunftsmotor.local','waltraud.gnatz'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs1','Prof.','Herlinde','Siering','herlinde.siering@HRO.zukunftsmotor.local','herlinde.siering'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs1','Univ.Prof.','Nelly','Fritsch','nelly.fritsch@HRO.zukunftsmotor.local','nelly.fritsch'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs2','Herr','Natali','Karz','natali.karz@HRO.zukunftsmotor.local','natali.karz'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs2','Prof.','Alfons','Heß','alfons.heß@HRO.zukunftsmotor.local','alfons.heß'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs3','Prof.','Victor','Radisch','victor.radisch@HRO.zukunftsmotor.local','victor.radisch'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs3','Dr.','Hans-Albert','Heuser','hans-albert.heuser@HRO.zukunftsmotor.local','hans-albert.heuser'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs4','Ing.','Andree','Holt','andree.holt@HRO.zukunftsmotor.local','andree.holt'),
('Rostock','18001','Beispielpfad 11','HRO','Kurs4','Dr.','Harold','Wiek','harold.wiek@HRO.zukunftsmotor.local','harold.wiek'),
('Rostock','18001','Beispielpfad 11','HRO','IT','Herr','Cecilia','Paffrath','cecilia.paffrath@HRO.zukunftsmotor.local','cecilia.paffrath'),
('Rostock','18001','Beispielpfad 11','HRO','IT','Dipl.-Ing.','Eugenie','Klingelhöfer','eugenie.klingelhöfer@HRO.zukunftsmotor.local','eugenie.klingelhöfer'),
('Köln','76131','Teststraße 12','K','Verwaltung','Dr.','Sibylla','Hänel','sibylla.hänel@K.zukunftsmotor.local','sibylla.hänel'),
('Köln','76131','Teststraße 12','K','Verwaltung','Univ.Prof.','Sigfried','Mans','sigfried.mans@K.zukunftsmotor.local','sigfried.mans'),
('Köln','76131','Teststraße 12','K','LX','Ing.','Alexandre','Mende','alexandre.mende@K.zukunftsmotor.local','alexandre.mende'),
('Köln','76131','Teststraße 12','K','LX','Ing.','Lili','Renner','lili.renner@K.zukunftsmotor.local','lili.renner'),
('Köln','76131','Teststraße 12','K','Kurs1','Ing.','Ellen','Schuchhardt','ellen.schuchhardt@K.zukunftsmotor.local','ellen.schuchhardt'),
('Köln','76131','Teststraße 12','K','Kurs1','Dr.','Isabella','Winkler','isabella.winkler@K.zukunftsmotor.local','isabella.winkler'),
('Köln','76131','Teststraße 12','K','Kurs2','Prof.','Erica','Gumprich','erica.gumprich@K.zukunftsmotor.local','erica.gumprich'),
('Köln','76131','Teststraße 12','K','Kurs2','Dipl.-Ing.','Karlfried','Lindau','karlfried.lindau@K.zukunftsmotor.local','karlfried.lindau'),
('Köln','76131','Teststraße 12','K','Kurs3','Frau','Katy','Koch','katy.koch@K.zukunftsmotor.local','katy.koch'),
('Köln','76131','Teststraße 12','K','Kurs3','Dr.','Heinz-Günter','Hornich','heinz-günter.hornich@K.zukunftsmotor.local','heinz-günter.hornich'),
('Köln','76131','Teststraße 12','K','Kurs4','Herr','Harald','Krause','harald.krause@K.zukunftsmotor.local','harald.krause'),
('Köln','76131','Teststraße 12','K','Kurs4','Herr','Andreas','Junitz','andreas.junitz@K.zukunftsmotor.local','andreas.junitz'),
('Köln','76131','Teststraße 12','K','IT','Herr','Claudio','van der Dussen','claudio.van der dussen@K.zukunftsmotor.local','claudio.van der dussen'),
('Köln','76131','Teststraße 12','K','IT','Univ.Prof.','Hans Peter','Lübs','hans peter.lübs@K.zukunftsmotor.local','hans peter.lübs');


INSERT INTO interessenten(Standort, PLZ, Adresse_Standort, KFZ, Abteilung, Anrede, Vorname, Nachname, EMail, Benutzeranmeldename) VALUES 
('Freiburg','79098','Musterweg 13','FR','Verwaltung','Prof.','Matthäus','Koch II','matthäus.koch ii@FR.zukunftsmotor.local','matthäus.koch ii'),
('Freiburg','79098','Musterweg 13','FR','Verwaltung','Ing.','Siegfried','Röhricht','siegfried.röhricht@FR.zukunftsmotor.local','siegfried.röhricht'),
('Freiburg','79098','Musterweg 13','FR','LX','Prof.','Helge','Kranz','helge.kranz@FR.zukunftsmotor.local','helge.kranz'),
('Freiburg','79098','Musterweg 13','FR','LX','Ing.','Lilli','Stey','lilli.stey@FR.zukunftsmotor.local','lilli.stey'),
('Freiburg','79098','Musterweg 13','FR','Kurs1','Herr','Cora','Vogt','cora.vogt@FR.zukunftsmotor.local','cora.vogt'),
('Freiburg','79098','Musterweg 13','FR','Kurs1','Frau','Tillmann','Hande','tillmann.hande@FR.zukunftsmotor.local','tillmann.hande'),
('Freiburg','79098','Musterweg 13','FR','Kurs2','Univ.Prof.','Jaroslaw','Etzold','jaroslaw.etzold@FR.zukunftsmotor.local','jaroslaw.etzold'),
('Freiburg','79098','Musterweg 13','FR','Kurs2','Ing.','Hans-H.','Hänel','hans-h..hänel@FR.zukunftsmotor.local','hans-h..hänel'),
('Freiburg','79098','Musterweg 13','FR','Kurs3','Prof.','Timo','Naser','timo.naser@FR.zukunftsmotor.local','timo.naser'),
('Freiburg','79098','Musterweg 13','FR','Kurs3','Frau','Udo','Albers','udo.albers@FR.zukunftsmotor.local','udo.albers'),
('Freiburg','79098','Musterweg 13','FR','Kurs4','Prof.','Milena','Bohlander','milena.bohlander@FR.zukunftsmotor.local','milena.bohlander'),
('Freiburg','79098','Musterweg 13','FR','Kurs4','Univ.Prof.','Diana','Knappe','diana.knappe@FR.zukunftsmotor.local','diana.knappe'),
('Freiburg','79098','Musterweg 13','FR','IT','Dipl.-Ing.','Fredi','Meister','fredi.meister@FR.zukunftsmotor.local','fredi.meister'),
('Freiburg','79098','Musterweg 13','FR','IT','Univ.Prof.','Erhardt','Schuchhardt','erhardt.schuchhardt@FR.zukunftsmotor.local','erhardt.schuchhardt'),
('Dortmund','44001','Beispielplatz 14','DO','Verwaltung','Herr','Waltraut','Junken','waltraut.junken@DO.zukunftsmotor.local','waltraut.junken'),
('Dortmund','44001','Beispielplatz 14','DO','Verwaltung','Dr.','Ruthild','Schönland','ruthild.schönland@DO.zukunftsmotor.local','ruthild.schönland'),
('Dortmund','44001','Beispielplatz 14','DO','LX','Frau','Curt','Häring','curt.häring@DO.zukunftsmotor.local','curt.häring'),
('Dortmund','44001','Beispielplatz 14','DO','LX','Dipl.-Ing.','Amelie','Butte','amelie.butte@DO.zukunftsmotor.local','amelie.butte'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs1','Frau','Amalia','Holsten','amalia.holsten@DO.zukunftsmotor.local','amalia.holsten'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs1','Frau','Alexa','Krebs','alexa.krebs@DO.zukunftsmotor.local','alexa.krebs'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs2','Ing.','Abdullah','Jungfer','abdullah.jungfer@DO.zukunftsmotor.local','abdullah.jungfer'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs2','Frau','Herrmann','Reuter','herrmann.reuter@DO.zukunftsmotor.local','herrmann.reuter'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs3','Frau','Marco','Steckel','marco.steckel@DO.zukunftsmotor.local','marco.steckel'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs3','Prof.','Marion','Tschentscher','marion.tschentscher@DO.zukunftsmotor.local','marion.tschentscher'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs4','Prof.','H.-Dieter','Stoll','h.-dieter.stoll@DO.zukunftsmotor.local','h.-dieter.stoll'),
('Dortmund','44001','Beispielplatz 14','DO','Kurs4','Prof.','Luigi','Seifert','luigi.seifert@DO.zukunftsmotor.local','luigi.seifert'),
('Dortmund','44001','Beispielplatz 14','DO','IT','Dr.','Alessandro','Rohleder','alessandro.rohleder@DO.zukunftsmotor.local','alessandro.rohleder'),
('Dortmund','44001','Beispielplatz 14','DO','IT','Dr.','Dunja','Matthäi','dunja.matthäi@DO.zukunftsmotor.local','dunja.matthäi'),
('Potsdam','14467','Testgasse 15','P','Verwaltung','Univ.Prof.','Olivia','Bärer','olivia.bärer@P.zukunftsmotor.local','olivia.bärer'),
('Potsdam','14467','Testgasse 15','P','Verwaltung','Frau','Wenzel','Briemer','wenzel.briemer@P.zukunftsmotor.local','wenzel.briemer'),
('Potsdam','14467','Testgasse 15','P','LX','Dr.','Ian','Hermighausen','ian.hermighausen@P.zukunftsmotor.local','ian.hermighausen'),
('Potsdam','14467','Testgasse 15','P','LX','Frau','Fatima','Scholz','fatima.scholz@P.zukunftsmotor.local','fatima.scholz'),
('Potsdam','14467','Testgasse 15','P','Kurs1','Ing.','Johannes','Scholl','johannes.scholl@P.zukunftsmotor.local','johannes.scholl'),
('Potsdam','14467','Testgasse 15','P','Kurs1','Herr','Silja','Scheuermann','silja.scheuermann@P.zukunftsmotor.local','silja.scheuermann'),
('Potsdam','14467','Testgasse 15','P','Kurs2','Dipl.-Ing.','Gino','Scholz','gino.scholz@P.zukunftsmotor.local','gino.scholz'),
('Potsdam','14467','Testgasse 15','P','Kurs2','Ing.','Maria','Boucsein','maria.boucsein@P.zukunftsmotor.local','maria.boucsein'),
('Potsdam','14467','Testgasse 15','P','Kurs3','Dr.','Freia','Kruschwitz','freia.kruschwitz@P.zukunftsmotor.local','freia.kruschwitz'),
('Potsdam','14467','Testgasse 15','P','Kurs3','Prof.','Karola','Ernst','karola.ernst@P.zukunftsmotor.local','karola.ernst'),
('Potsdam','14467','Testgasse 15','P','Kurs4','Ing.','Theodora','Hecker','theodora.hecker@P.zukunftsmotor.local','theodora.hecker'),
('Potsdam','14467','Testgasse 15','P','Kurs4','Ing.','Marvin','Buchholz','marvin.buchholz@P.zukunftsmotor.local','marvin.buchholz'),
('Potsdam','14467','Testgasse 15','P','IT','Herr','Guenther','Wulf','guenther.wulf@P.zukunftsmotor.local','guenther.wulf'),
('Potsdam','14467','Testgasse 15','P','IT','Univ.Prof.','Siegmund','Drubin','siegmund.drubin@P.zukunftsmotor.local','siegmund.drubin'),
('Leipzig','04001','Musterweg 16','L','Verwaltung','Dr.','Theodor','Johann','theodor.johann@L.zukunftsmotor.local','theodor.johann'),
('Leipzig','04001','Musterweg 16','L','Verwaltung','Ing.','Carmelo','Gertz','carmelo.gertz@L.zukunftsmotor.local','carmelo.gertz'),
('Leipzig','04001','Musterweg 16','L','LX','Univ.Prof.','Ana','Fiebig','ana.fiebig@L.zukunftsmotor.local','ana.fiebig'),
('Leipzig','04001','Musterweg 16','L','LX','Univ.Prof.','Willibald','Stiffel','willibald.stiffel@L.zukunftsmotor.local','willibald.stiffel'),
('Leipzig','04001','Musterweg 16','L','Kurs1','Ing.','Mathias','Gerlach','mathias.gerlach@L.zukunftsmotor.local','mathias.gerlach'),
('Leipzig','04001','Musterweg 16','L','Kurs1','Prof.','Joseph','Trommler','joseph.trommler@L.zukunftsmotor.local','joseph.trommler'),
('Leipzig','04001','Musterweg 16','L','Kurs2','Ing.','Nevenka','Klingelhöfer','nevenka.klingelhöfer@L.zukunftsmotor.local','nevenka.klingelhöfer'),
('Leipzig','04001','Musterweg 16','L','Kurs2','Univ.Prof.','Telse','Lorch','telse.lorch@L.zukunftsmotor.local','telse.lorch'),
('Leipzig','04001','Musterweg 16','L','Kurs3','Prof.','Marion','Plath','marion.plath@L.zukunftsmotor.local','marion.plath'),
('Leipzig','04001','Musterweg 16','L','Kurs3','Frau','Bastian','Schuster','bastian.schuster@L.zukunftsmotor.local','bastian.schuster'),
('Leipzig','04001','Musterweg 16','L','Kurs4','Univ.Prof.','Dörte','Stiebitz','dörte.stiebitz@L.zukunftsmotor.local','dörte.stiebitz'),
('Leipzig','04001','Musterweg 16','L','Kurs4','Herr','Maik','Biggen','maik.biggen@L.zukunftsmotor.local','maik.biggen'),
('Leipzig','04001','Musterweg 16','L','IT','Dipl.-Ing.','Edda','Zobel','edda.zobel@L.zukunftsmotor.local','edda.zobel'),
('Leipzig','04001','Musterweg 16','L','IT','Prof.','Gunnar','Kroker','gunnar.kroker@L.zukunftsmotor.local','gunnar.kroker'),
('Mannheim','68001','Beispielstraße 17','MA','Verwaltung','Ing.','Maya','Otto','maya.otto@MA.zukunftsmotor.local','maya.otto'),
('Mannheim','68001','Beispielstraße 17','MA','Verwaltung','Prof.','Swetlana','Aumann','swetlana.aumann@MA.zukunftsmotor.local','swetlana.aumann'),
('Mannheim','68001','Beispielstraße 17','MA','LX','Dipl.-Ing.','Rouven','Ortmann','rouven.ortmann@MA.zukunftsmotor.local','rouven.ortmann'),
('Mannheim','68001','Beispielstraße 17','MA','LX','Univ.Prof.','Benita','Blümel','benita.blümel@MA.zukunftsmotor.local','benita.blümel'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs1','Univ.Prof.','Flora','Finke','flora.finke@MA.zukunftsmotor.local','flora.finke'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs1','Herr','Frithjof','Gierschner','frithjof.gierschner@MA.zukunftsmotor.local','frithjof.gierschner'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs2','Dipl.-Ing.','Roswitha','Rohleder','roswitha.rohleder@MA.zukunftsmotor.local','roswitha.rohleder'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs2','Univ.Prof.','Tilo','Mitschke','tilo.mitschke@MA.zukunftsmotor.local','tilo.mitschke'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs3','Univ.Prof.','Istvan','Scheibe','istvan.scheibe@MA.zukunftsmotor.local','istvan.scheibe'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs3','Ing.','Zenta','Jopich','zenta.jopich@MA.zukunftsmotor.local','zenta.jopich'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs4','Univ.Prof.','Annelie','Reuter','annelie.reuter@MA.zukunftsmotor.local','annelie.reuter'),
('Mannheim','68001','Beispielstraße 17','MA','Kurs4','Dipl.-Ing.','Dariusz','Krebs','dariusz.krebs@MA.zukunftsmotor.local','dariusz.krebs'),
('Mannheim','68001','Beispielstraße 17','MA','IT','Univ.Prof.','Kristian','Spieß','kristian.spieß@MA.zukunftsmotor.local','kristian.spieß'),
('Mannheim','68001','Beispielstraße 17','MA','IT','Univ.Prof.','Brunhilde','van der Dussen','brunhilde.van der dussen@MA.zukunftsmotor.local','brunhilde.van der dussen'),
('Mainz','55116','Testweg 18','MZ','Verwaltung','Herr','Tabea','Boucsein','tabea.boucsein@MZ.zukunftsmotor.local','tabea.boucsein'),
('Mainz','55116','Testweg 18','MZ','Verwaltung','Ing.','Dorina','Mende','dorina.mende@MZ.zukunftsmotor.local','dorina.mende'),
('Mainz','55116','Testweg 18','MZ','LX','Herr','Ignaz','Dippel','ignaz.dippel@MZ.zukunftsmotor.local','ignaz.dippel'),
('Mainz','55116','Testweg 18','MZ','LX','Dr.','Maya','Salz','maya.salz@MZ.zukunftsmotor.local','maya.salz'),
('Mainz','55116','Testweg 18','MZ','Kurs1','Ing.','Hans-Heinrich','Dussen van','hans-heinrich.dussen van@MZ.zukunftsmotor.local','hans-heinrich.dussen van'),
('Mainz','55116','Testweg 18','MZ','Kurs1','Prof.','Pascal','Römer','pascal.römer@MZ.zukunftsmotor.local','pascal.römer'),
('Mainz','55116','Testweg 18','MZ','Kurs2','Prof.','Ferenc','Krein','ferenc.krein@MZ.zukunftsmotor.local','ferenc.krein'),
('Mainz','55116','Testweg 18','MZ','Kurs2','Ing.','Herta','Kühnert','herta.kühnert@MZ.zukunftsmotor.local','herta.kühnert'),
('Mainz','55116','Testweg 18','MZ','Kurs3','Herr','Leonie','Hering','leonie.hering@MZ.zukunftsmotor.local','leonie.hering'),
('Mainz','55116','Testweg 18','MZ','Kurs3','Univ.Prof.','Hans-Eberhard','Eimer','hans-eberhard.eimer@MZ.zukunftsmotor.local','hans-eberhard.eimer'),
('Mainz','55116','Testweg 18','MZ','Kurs4','Dipl.-Ing.','Emil','Holsten','emil.holsten@MZ.zukunftsmotor.local','emil.holsten'),
('Mainz','55116','Testweg 18','MZ','Kurs4','Dr.','Kira','Trub','kira.trub@MZ.zukunftsmotor.local','kira.trub'),
('Mainz','55116','Testweg 18','MZ','IT','Univ.Prof.','Mijo','Wähner','mijo.wähner@MZ.zukunftsmotor.local','mijo.wähner'),
('Mainz','55116','Testweg 18','MZ','IT','Univ.Prof.','Erich','Eckbauer','erich.eckbauer@MZ.zukunftsmotor.local','erich.eckbauer'),
('Karlsruhe','76131','Musterstraße 19','KA','Verwaltung','Dr.','Erdmute','Heintze','erdmute.heintze@KA.zukunftsmotor.local','erdmute.heintze'),
('Karlsruhe','76131','Musterstraße 19','KA','Verwaltung','Ing.','Frida','Faust','frida.faust@KA.zukunftsmotor.local','frida.faust'),
('Karlsruhe','76131','Musterstraße 19','KA','LX','Ing.','Stefani','Naser','stefani.naser@KA.zukunftsmotor.local','stefani.naser'),
('Karlsruhe','76131','Musterstraße 19','KA','LX','Univ.Prof.','Enrico','Sorgatz','enrico.sorgatz@KA.zukunftsmotor.local','enrico.sorgatz'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs1','Dr.','Roger','Henck','roger.henck@KA.zukunftsmotor.local','roger.henck'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs1','Herr','Claudio','Trupp','claudio.trupp@KA.zukunftsmotor.local','claudio.trupp'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs2','Dr.','Amanda','Möchlichen','amanda.möchlichen@KA.zukunftsmotor.local','amanda.möchlichen'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs2','Frau','Philomena','Salz','philomena.salz@KA.zukunftsmotor.local','philomena.salz'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs3','Dr.','Sylvia','Schweitzer','sylvia.schweitzer@KA.zukunftsmotor.local','sylvia.schweitzer'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs3','Herr','Antonio','Seifert','antonio.seifert@KA.zukunftsmotor.local','antonio.seifert'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs4','Prof.','Susan','Gehringer','susan.gehringer@KA.zukunftsmotor.local','susan.gehringer'),
('Karlsruhe','76131','Musterstraße 19','KA','Kurs4','Frau','Anatol','Niemeier','anatol.niemeier@KA.zukunftsmotor.local','anatol.niemeier'),
('Karlsruhe','76131','Musterstraße 19','KA','IT','Herr','Harry','Kabus','harry.kabus@KA.zukunftsmotor.local','harry.kabus'),
('Karlsruhe','76131','Musterstraße 19','KA','IT','Dipl.-Ing.','Augustin','Weller','augustin.weller@KA.zukunftsmotor.local','augustin.weller'),
('Minden','32423','Beispielpfad 20','MI','Verwaltung','Ing.','Karl-Peter','Stiebitz','karl-peter.stiebitz@MI.zukunftsmotor.local','karl-peter.stiebitz'),
('Minden','32423','Beispielpfad 20','MI','Verwaltung','Dipl.-Ing.','Paola','Kroker','paola.kroker@MI.zukunftsmotor.local','paola.kroker'),
('Minden','32423','Beispielpfad 20','MI','LX','Herr','Kirsten','Neuschäfer','kirsten.neuschäfer@MI.zukunftsmotor.local','kirsten.neuschäfer'),
('Minden','32423','Beispielpfad 20','MI','LX','Ing.','Sibylle','Lorch','sibylle.lorch@MI.zukunftsmotor.local','sibylle.lorch'),
('Minden','32423','Beispielpfad 20','MI','Kurs1','Univ.Prof.','Johanna','Butte','johanna.butte@MI.zukunftsmotor.local','johanna.butte'),
('Minden','32423','Beispielpfad 20','MI','Kurs1','Univ.Prof.','Nicolaus','Eimer','nicolaus.eimer@MI.zukunftsmotor.local','nicolaus.eimer'),
('Minden','32423','Beispielpfad 20','MI','Kurs2','Prof.','Ralf-Dieter','Neuschäfer','ralf-dieter.neuschäfer@MI.zukunftsmotor.local','ralf-dieter.neuschäfer'),
('Minden','32423','Beispielpfad 20','MI','Kurs2','Frau','Luzia','Albers','luzia.albers@MI.zukunftsmotor.local','luzia.albers'),
('Minden','32423','Beispielpfad 20','MI','Kurs3','Dr.','Torben','Rogge','torben.rogge@MI.zukunftsmotor.local','torben.rogge'),
('Minden','32423','Beispielpfad 20','MI','Kurs3','Frau','Karina','Klapp','karina.klapp@MI.zukunftsmotor.local','karina.klapp'),
('Minden','32423','Beispielpfad 20','MI','Kurs4','Dipl.-Ing.','Luciano','Birnbaum','luciano.birnbaum@MI.zukunftsmotor.local','luciano.birnbaum'),
('Minden','32423','Beispielpfad 20','MI','Kurs4','Dipl.-Ing.','Ferenc','Röhrdanz','ferenc.röhrdanz@MI.zukunftsmotor.local','ferenc.röhrdanz'),
('Minden','32423','Beispielpfad 20','MI','IT','Ing.','Eva-Maria','Holzapfel','eva-maria.holzapfel@MI.zukunftsmotor.local','eva-maria.holzapfel'),
('Minden','32423','Beispielpfad 20','MI','IT','Univ.Prof.','Otmar','Mohaupt','otmar.mohaupt@MI.zukunftsmotor.local','otmar.mohaupt'),
('Flensburg','24901','Testgasse 21','FL','Verwaltung','Ing.','Milan','Hethur','milan.hethur@FL.zukunftsmotor.local','milan.hethur'),
('Flensburg','24901','Testgasse 21','FL','Verwaltung','Dipl.-Ing.','Tania','Mangold','tania.mangold@FL.zukunftsmotor.local','tania.mangold'),
('Flensburg','24901','Testgasse 21','FL','LX','Herr','Bianka','Gertz','bianka.gertz@FL.zukunftsmotor.local','bianka.gertz'),
('Flensburg','24901','Testgasse 21','FL','LX','Ing.','Viola','Söding','viola.söding@FL.zukunftsmotor.local','viola.söding'),
('Flensburg','24901','Testgasse 21','FL','Kurs1','Dipl.-Ing.','Melanie','Binner','melanie.binner@FL.zukunftsmotor.local','melanie.binner'),
('Flensburg','24901','Testgasse 21','FL','Kurs1','Univ.Prof.','Gilda','Stahr','gilda.stahr@FL.zukunftsmotor.local','gilda.stahr'),
('Flensburg','24901','Testgasse 21','FL','Kurs2','Herr','Erol','Stoll','erol.stoll@FL.zukunftsmotor.local','erol.stoll'),
('Flensburg','24901','Testgasse 21','FL','Kurs2','Dipl.-Ing.','Corinne','Weinhage','corinne.weinhage@FL.zukunftsmotor.local','corinne.weinhage'),
('Flensburg','24901','Testgasse 21','FL','Kurs3','Ing.','Sylvie','Kranz','sylvie.kranz@FL.zukunftsmotor.local','sylvie.kranz'),
('Flensburg','24901','Testgasse 21','FL','Kurs3','Prof.','Heiner','Rudolph','heiner.rudolph@FL.zukunftsmotor.local','heiner.rudolph'),
('Flensburg','24901','Testgasse 21','FL','Kurs4','Ing.','Isabelle','Killer','isabelle.killer@FL.zukunftsmotor.local','isabelle.killer'),
('Flensburg','24901','Testgasse 21','FL','Kurs4','Univ.Prof.','Ingbert','Rörricht','ingbert.rörricht@FL.zukunftsmotor.local','ingbert.rörricht'),
('Flensburg','24901','Testgasse 21','FL','IT','Dr.','Dietlind','Christoph','dietlind.christoph@FL.zukunftsmotor.local','dietlind.christoph'),
('Flensburg','24901','Testgasse 21','FL','IT','Dr.','Liselotte','Müller','liselotte.müller@FL.zukunftsmotor.local','liselotte.müller'),
('Konstanz','76462','Musterweg 22','KN','Verwaltung','Dr.','Pietro','Striebitz','pietro.striebitz@KN.zukunftsmotor.local','pietro.striebitz'),
('Konstanz','76462','Musterweg 22','KN','Verwaltung','Dipl.-Ing.','Gabriela','Mülichen','gabriela.mülichen@KN.zukunftsmotor.local','gabriela.mülichen'),
('Konstanz','76462','Musterweg 22','KN','LX','Univ.Prof.','Dolores','Henck','dolores.henck@KN.zukunftsmotor.local','dolores.henck'),
('Konstanz','76462','Musterweg 22','KN','LX','Prof.','Jutta','Haase','jutta.haase@KN.zukunftsmotor.local','jutta.haase'),
('Konstanz','76462','Musterweg 22','KN','Kurs1','Univ.Prof.','Roderich','Förster','roderich.förster@KN.zukunftsmotor.local','roderich.förster'),
('Konstanz','76462','Musterweg 22','KN','Kurs1','Prof.','Uli','Eberth','uli.eberth@KN.zukunftsmotor.local','uli.eberth'),
('Konstanz','76462','Musterweg 22','KN','Kurs2','Dipl.-Ing.','Meik','Kambs','meik.kambs@KN.zukunftsmotor.local','meik.kambs'),
('Konstanz','76462','Musterweg 22','KN','Kurs2','Univ.Prof.','Reni','Lindner','reni.lindner@KN.zukunftsmotor.local','reni.lindner'),
('Konstanz','76462','Musterweg 22','KN','Kurs3','Prof.','Swetlana','Schmidtke','swetlana.schmidtke@KN.zukunftsmotor.local','swetlana.schmidtke'),
('Konstanz','76462','Musterweg 22','KN','Kurs3','Dipl.-Ing.','Klara','Naser','klara.naser@KN.zukunftsmotor.local','klara.naser'),
('Konstanz','76462','Musterweg 22','KN','Kurs4','Univ.Prof.','Hubert','Schleich','hubert.schleich@KN.zukunftsmotor.local','hubert.schleich'),
('Konstanz','76462','Musterweg 22','KN','Kurs4','Frau','Klaus-Michael','Hübel','klaus-michael.hübel@KN.zukunftsmotor.local','klaus-michael.hübel'),
('Konstanz','76462','Musterweg 22','KN','IT','Prof.','Theobald','Adler','theobald.adler@KN.zukunftsmotor.local','theobald.adler'),
('Konstanz','76462','Musterweg 22','KN','IT','Univ.Prof.','Mikhail','Gorlitz','mikhail.gorlitz@KN.zukunftsmotor.local','mikhail.gorlitz');